version: '3'

services:
  csd:
    container_name: kleer-csd
    #build: . use this, if you change the dockerfile
    image: yamitcar/csd:ruby2.6.5
    tty: true
    ports:
      - '0.0.0.0:4567:4567'
      - '0.0.0.0:1234:1234'
      - '0.0.0.0:26162:26162'
    volumes:
      - .:/CSD/projects